//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursal
    {
        public int id { get; set; }
        public Nullable<int> idMunicipio { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual empresa empresa { get; set; }
        public virtual municipio municipio { get; set; }
    }
}
